package com.slzh.xd.sqlmapper;

import com.slzh.xd.model.DataCount;

public interface DataCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    int insert(DataCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    int insertSelective(DataCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    DataCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_count
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataCount record);
}