package com.slzh.xd.sqlmapper;

import com.slzh.xd.model.InterfaceInfo;

public interface InterfaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long interfaceInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    int insert(InterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    int insertSelective(InterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    InterfaceInfo selectByPrimaryKey(Long interfaceInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_interface_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InterfaceInfo record);
}