package com.slzh.xd.model;

import java.util.Date;

public class DataCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.data_coun
     *
     * @mbggenerated
     */
    private Integer dataCoun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.createtime
     *
     * @mbggenerated
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_count.catm
     *
     * @mbggenerated
     */
    private String catm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.id
     *
     * @return the value of t_data_count.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.id
     *
     * @param id the value for t_data_count.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.data_type
     *
     * @return the value of t_data_count.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.data_type
     *
     * @param dataType the value for t_data_count.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.data_coun
     *
     * @return the value of t_data_count.data_coun
     *
     * @mbggenerated
     */
    public Integer getDataCoun() {
        return dataCoun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.data_coun
     *
     * @param dataCoun the value for t_data_count.data_coun
     *
     * @mbggenerated
     */
    public void setDataCoun(Integer dataCoun) {
        this.dataCoun = dataCoun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.createtime
     *
     * @return the value of t_data_count.createtime
     *
     * @mbggenerated
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.createtime
     *
     * @param createtime the value for t_data_count.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.updateTime
     *
     * @return the value of t_data_count.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.updateTime
     *
     * @param updatetime the value for t_data_count.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_count.catm
     *
     * @return the value of t_data_count.catm
     *
     * @mbggenerated
     */
    public String getCatm() {
        return catm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_count.catm
     *
     * @param catm the value for t_data_count.catm
     *
     * @mbggenerated
     */
    public void setCatm(String catm) {
        this.catm = catm == null ? null : catm.trim();
    }
}